CREATE TABLE IF NOT EXISTS `tagged` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "Unique ID of the property",
    `entity` INT UNSIGNED NOT NULL COMMENT "Entity Id",
    `tag` INT UNSIGNED NOT NULL COMMENT "Tag Id",
	INDEX (`entity`, `tag`),
	PRIMARY KEY (`id`),
	UNIQUE (`id`),
	UNIQUE (`entity`, `tag`),
	FOREIGN KEY (`entity`) REFERENCES `entity` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (`tag`) REFERENCES `tag` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ENGINE=InnoDB;


