<?php echo $this->doctype()?>
<?php
    $this->headMeta()
        ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendHttpEquiv('Cache-Control', 'no-cache')
        ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
		$this->includeJS('jquery.js');
        $this->includeJS('masonry.js');
        $this->includeJS('follow.js');
		$this->includeCSS('layout.css');
?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
	<?php echo $this->headTitle()?>
	<?php echo $this->headMeta()?>
	<?php echo $this->headLink()?>
	<?php echo $this->headScript()?>
	<?php echo $this->headStyle()?>
	<style>
		@import url("http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");
	</style>
</head> 
<body>
    <div class="menu-panel" id="menu-panel">
        <h3><i class="fa fa-check-circle"></i> Popular</h3>
        <ul class="menu">
            <li><a class="<?=$this->mainTag == "What's hot" ? "current":""?>" href="<?=$this->url(array(), "browse", false)?>"><i class="fa fa-fire"></i> What's hot</a></li>
            <li><a class="<?=$this->mainTag == "Startups" ? "current":""?>" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Startups")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><i class="fa fa-rocket"></i> Startups</a></li>
            <li><a class="<?=$this->mainTag == "Entreprenuers" ? "current":""?>" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Entreprenuers")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><i class="fa fa-smile-o"></i> Entreprenuers</a></li>
            <li><a class="<?=$this->mainTag == "Known people" ? "current":""?>" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Known people")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><i class="fa fa-smile-o"></i> Known people</a></li>
            <li><a class="<?=$this->mainTag == "Sportsmen" ? "current":""?>" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Sportsmen")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><i class="fa fa-star"></i> Sportsmen</a></li>
            <li><a class="<?=$this->mainTag == "Global trends" ? "current":""?>" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Global trends")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><i class="fa fa-folder-open"></i> Global trends</a></li>
        </ul>
        <div class="legal-notes">
            TWENTYTAGS.COM<br/>
            COPYRIGHT 2014
        </div>
    </div>
    <div class="page-container" id="page-container">
    </div>
<body>
</html>
