<?$this->headTitle("TwentyTags - Добавьте тег")?>
    <h1 class="info">добавьте тег, <?=Model_User::me()->nickname?></h1>
    <p class="lighten-text">
        Добавьте тег, по которому Вы хотите получать новости
    </p>
    <div class="button-iconed">
        <i class="icon-pencil lighten-text"></i>
        <input type="text" id="tag-value" class="text-field f-span6 input-large" placeholder="Ваш новый тег">
    </div>
    <p id="error-message" class="success">
    </p>
    <p class="lighten-text">
        После того, как Вы добавите тег, мы начнем получать по нему новости. Они будут появляться в разделе <span class="warning">Новости</span>. Также
        этот тег будет доступен любому пользователю нашего ресурса
    </p>

<script>
    $(document).ready(function() {
        $("#tag-value").keypress(function(event) {
            if ( event.which == 13 ) {
                $.post(
                    "<?=$this->url(array('controller'=>'index', 'action'=>'addusertag'), 'default', true)?>",
                    { 'tag': $("#tag-value").val() },
                    function(data) {
                        if (data == "OK") {
                            location.href = "following";
                        } else {
                            $("#error-message").html(data);
                        }
                    }
                )
            }
        });
    })
</script>