<?$this->headTitle("TwentyTags - Регистрация")?>
<div class="container padding-around-base">
    <p class="medium lighten-text">Вы хотите подписаться на тег <i class="icon-hash warning"></i> <span class="info"><?=$this->tag->title?></span>, но Вы не зарегистрированы или не вошли</p>
    <br/>
    <p class="lighten-text">
        Для регистрации просто придумайте ник. Для входа введите его. Потом нажмите <span class="warning code">Enter</span>
    </p>
    <?=$this->partial("partials/register.phtml", array("tag"=>$this->tag))?>
</div>