<?$this->headTitle("TwentyTags - Add tag")?>
<div class="message-container">
    <p class="margins">
        Add any tag you would like to get updates about. We will review and
        add it very soon
    </p>
    <input type="text" id="tag-value" class="input-text input-large" placeholder="Type tag & hit enter">
    <p id="error-message">
    </p>
</div>

<script>
    $(document).ready(function() {
        $("#tag-value").keypress(function(event) {
            if ( event.which == 13 ) {
                $.post(
                    "<?=$this->url(array('controller'=>'index', 'action'=>'addusertag'), 'default', true)?>",
                    { 'tag': $("#tag-value").val() },
                    function(data) {
                        if (data == "OK") {
                            location.href = "following";
                        } else {
                            $("#error-message").html(data);
                        }
                    }
                )
            }
        });
    })
</script>