<?$this->headTitle("TwentyTags - ".Model_User::me()->nickname)?>
<div class="container padding-around-base">
    <h1 class="info capitalize">привет, <?=Model_User::me()->nickname?>!</h1>
    <p class="lighten-text">
        Вы не подписаны ни на один тег. Попробуйте выбрать из этих разделов
    </p>
    <?=$this->partial("partials/chapters.phtml")?>
    <br/>
    <button class="button-info f-span4" onclick="location.href='<?=$this->url(array(), "addtag", true)?>'">добавить свой тег</button>
</div>