<?$this->headTitle("TwentyTags - ".Model_User::me()->nickname)?>
<div class="container padding-around-base">
    <h2 class="info capitalize">Привет, <?=Model_User::me()->nickname?>!</h2>
    <p class="lighten-text">
        Пока никаких новостей нет. Может Вы не подписались ни на что? Попробуйте эти разделы
    </p>
    <?=$this->partial("partials/chapters.phtml")?>
    <br/>
    <button class="button-info f-span4" onclick="location.href='<?=$this->url(array(), "addtag", true)?>'">добавить свой тег</button>
</div>