<div class="message-container">
    <div class="message-title">
        You're not following any tags
    </div>
    <div class="message-description">
        Browse tags by category and follow some to get updates
    </div>
    <div class="button-block">
        <button onclick="location.href='<?=$this->url(array(), "browse", false)?>'" class="btn-large btn-red">Browse tags</button>
    </div>
</div>