<?
    $this->headTitle("TwentyTags - ".$this->entity->title);
    $this->headMeta()->appendName('keywords', $this->escape($this->entity->title));
    $this->headMeta()->appendName('description', $this->escape("News about ".$this->entity->title));
    $this->headAnything()->addHtml('<meta property="og:title" content="'.$this->escape($this->entity->title).'">');
    $this->headAnything()->addHtml('<meta property="og:description" content="'.$this->escape($this->entity->description).'">');
    $this->headAnything()->addHtml('<meta property="og:image" content="'.$this->staticFile("images/entities/".$this->entity->picture).'">');
?>
<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>

<div class="toTop">
        <i class="btn-icon fa fa-angle-double-up"></i>
</div>
<div class="entity-container">
    <div class="entity">
        <img src="<?=$this->staticFile("images/entities/".$this->entity->picture)?>">
        <h2><?=$this->entity->title?></h2>
        <p>
                <?$tagged = Model_Tag::retrieveTaggedTagsByEntity($this->entity);?>
                <? foreach ($tagged as $tag):?>
                    <a class="gray-link link-underline" href="<?=$this->url(array("id"=>$tag, Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><?=$tag->value?></a>&#160;
                <? endforeach?>
        </p>
        <p class="margins">
            <a target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=640,height=300')"
               href="http://www.facebook.com/sharer/sharer.php?u=http://twentytags.com<?=$this->url(array("id"=>$this->entity, Model_Static_Functions::dashString($this->entity->title)=>""), "entity", false)?>">
                <i class="facebook fa fa-facebook-square"></i>
            </a>
            <a target="_blank" onclick="return !window.open(this.href, 'Twitter', 'width=640,height=300')"
               href="https://twitter.com/share">
                <i class="twitter fa fa-twitter-square"></i>
            </a>
            <a target="_blank" onclick="return !window.open(this.href, 'Google+', 'width=640,height=300')"
               href="https://plus.google.com/share?url=http://twentytags.com<?=$this->url(array("id"=>$this->entity, Model_Static_Functions::dashString($this->entity->title)=>""), "entity", false)?>">
                <i class="google fa fa-google-plus-square"></i>
            </a>
        </p>
        <p class="margins">
            <?=$this->entity->description?>
        </p>
        <?if (!Model_User::isLoggedIn()): ?>
            <?$isLogged = "user-not-logged";?>
            <div class="login-urls" id="login-url-<?=$this->entity?>">
                <?
                $loginUrl = $facebook->getLoginUrl(array(
                    "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login", "follow"=>$this->entity), "login", false)
                ));
                echo $loginUrl;
                ?>
            </div>

        <?endif?>
        <button id="follow-<?=$this->entity?>" class="to-follow-button <?=$isLogged?> btn-large">Follow</button>
        <br/>
        <br/>
    </div>
    <div class="alerts <?if (count($this->alerts) == 0) { echo "add-no-alerts-margin"; }?>">
        <?if (count($this->alerts) > 0):?>
            <? foreach ($this->alerts as $item):?>
                <article class="alert">
                    <h3>
                        <a class="red-link" href="<?=$item->link?>"><?=$item->title?></a>
                        <? if ($item->source == "youtube"):?>
                            <i class="fa fa-youtube-play"></i>
                        <? endif;?>
                    </h3>
                    <h5><?=date("F jS, Y",strtotime($item->added));?></h5>
                    <p class="margins">
                        <?=$item->body?>
                    </p>
                </article>
            <?endforeach?>
        <?else:?>
            <div class="message">
                <h1>
                    <i class="fa fa-clock-o"></i><br/>
                    There is no updates yet
                </h1>
                <p>
                    We've got to wait a little. Either follow this tag or get back later
                </p>
            </div>
        <?endif?>
    </div>
</div>
<script>
    $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y > 800) {
            $('.toTop').fadeIn();
        } else {
            $('.toTop').fadeOut();
        }
    });

    $(document).ready (function() {
        $("#to-top-button").click(function() {
            $('html, body').animate({ scrollTop: 0 }, 'slow');
        });
    });

    $(".to-follow-button").FollowEntity();
</script>