<?
    $this->headTitle("TwentyTags - ".$this->entity->title);
    $this->headMeta()->appendName('keywords', $this->escape($this->entity->title));
    $this->headMeta()->appendName('description', $this->escape("News about ".$this->entity->title));
    $this->headAnything()->addHtml('<meta property="og:title" content="'.$this->escape($this->entity->title).'">');
    $this->headAnything()->addHtml('<meta property="og:description" content="'.$this->escape($this->entity->description).'">');
    $this->headAnything()->addHtml('<meta property="og:image" content="'.$this->staticFile("images/entities/".$this->entity->picture).'">');
?>
<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>

    <div class="container">
        <div class="mobile-span9 lighten-text">
            <h1 class="info lower"><i class="icon-hash warning"></i><?=$this->entity->title?></h1>
            <?$tagged = Model_Tag::retrieveTaggedTagsByEntity($this->entity);?>
            <p class="no-padding">
            <? foreach ($tagged as $tag):?>
                <a class="info lower" href="<?=$this->url(array("id"=>$tag, Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><?=$tag->value?></a>&#160;
            <? endforeach?>
            </p>
            <p>
<!--            статей <span class="success medium">180</span>&#160;сегодня <span class="warning medium">7</span>-->
            <a class="no-underline" target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=640,height=300')"
               href="http://www.facebook.com/sharer/sharer.php?u=http://twentytags.com<?=$this->url(array("id"=>$this->entity, Model_Static_Functions::dashString($this->entity->title)=>""), "entity", false)?>">
                <i class="medium lighten-text fa fa-facebook"></i>
            </a>
            <a class="no-underline" target="_blank" onclick="return !window.open(this.href, 'Twitter', 'width=640,height=300')"
               href="https://twitter.com/share">
                <i class="medium lighten-text fa fa-twitter"></i>
            </a>
            <a class="no-underline" target="_blank" onclick="return !window.open(this.href, 'Google+', 'width=640,height=300')"
               href="https://plus.google.com/share?url=http://twentytags.com<?=$this->url(array("id"=>$this->entity, Model_Static_Functions::dashString($this->entity->title)=>""), "entity", false)?>">
                <i class="medium lighten-text fa fa-google-plus"></i>
            </a>
            </p>
        </div>
        <div class="mobile-span3 no-wrap right">
            <?if (!Model_User::isLoggedIn()): ?>
                <?$isLogged = "user-not-logged";?>
                <div class="login-urls" id="login-url-<?=$this->entity?>">
                    <?
                    $loginUrl = $facebook->getLoginUrl(array(
                        "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login", "follow"=>$this->entity), "login", false)
                    ));
                    $loginUrl = $this->url(array("tag"=>$this->entity), "addtagsignup", true);
                    echo $loginUrl;
                    ?>
                </div>
            <?endif?>
            <? $isSaved = Model_Entity::isSaved($this->entity);?>
            <button id="follow-<?=$this->entity?>" class="button-success button-medium f-span12 capitalize to-follow-button <?=$isLogged?> <?=$isSaved ? " followed button-default":""?>">
                <i class="icon-tag"></i>
                <span class="desktop-and-medium-only"><?=$isSaved ? "Отписаться" : "Подписаться"?></span>
            </button>
        </div>
     </div>

<?if ($this->entity->alerts == 0):?>
    <div class="container padding-around-small">
    <p class="lighten-text">
        Пока никаких новостей по этому тегу нет. Посмотрите пока другие разделы. Возможно Вам будет интересно
    </p>
    <a class="medium info" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Политика")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>">Политика</a><br/>
    <a class="medium info" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Стартапы")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>">Стартапы</a><br/>
    <a class="medium info" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Предприниматели")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>">Предприниматели</a><br/>
    <a class="medium info" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Известные Люди")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>">Известные люди</a><br/>
    <a class="medium info" href="<?=$this->url(array("id"=>($tag = Model_Tag::findByValue("Тренды")), Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>">Тренды</a><br/>
    </div>
<?else:?>
    <?=$this->partial("partials/morealerts.phtml", array("alerts"=>$this->alerts, "mode"=> "entity", "entity" => $this->entity));?>
<?endif?>

<script>
    var now = new Date().getTime();
    $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y > 800) {
            $('.toTop').fadeIn();
        } else {
            $('.toTop').fadeOut();
        }
        if (y >= ($(document).height() - $(window).height())) {
            if (new Date().getTime() - now > 1000) {
                var offset = $(window).data("offset");
                var url = "<?=$this->url(array('controller' => 'index', 'action' => 'morealerts'), 'default', true)?>";
                var loadUrl = url + '/offset/' + offset + '/entity/' + <?=$this->entity?>;
                loadMore(loadUrl);
                now = new Date().getTime();
            }
        }
    });
    $(document).ready (function() {
        $(window).data("offset", "20");
    });
    $(".to-follow-button").FollowEntity();
</script>
