<?$this->headTitle("TwentyTags - Feed")?>
<div class="padding-large">
    <form action="<?=$this->url(array(), "browse")?>" method="get">
        <div class="button-iconed">
            <i class="icon-search lighten-text"></i>
            <input type="text" name="key" id="tag-value" class="text-field f-span12 input-large" placeholder="Поиск тегов">
        </div>
    </form>
    <?=$this->partial("partials/morealerts.phtml", array("alerts"=>$this->alerts));?>
</div>
<script>
    var now = new Date().getTime();
    $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y >= ($(document).height() - $(window).height())) {
            if (new Date().getTime() - now > 1000) {
                var offset = $(window).data("offset");
                var url = "<?=$this->url(array('controller' => 'index', 'action' => 'morealerts'), 'default', true)?>";
                var loadUrl = url + '/offset/' + offset;
                loadMore(loadUrl);
                now = new Date().getTime();
            }
        }
    });
    $(document).ready (function() {
        $(window).data("offset", "20");
        $("#to-top-button").click(function() {
            $('html, body').animate({ scrollTop: 0 }, 'slow');
        });
    });
</script>