<div class="feed-container">
        <? foreach ($this->alerts as $item):?>
                <div class="alert-container">
                    <div class="entity">
                        <?=$item->entity->title?><br/>
                        <span class="date"><?=date("F jS, Y",strtotime($item->added));?></span>
                        <img src="<?=$this->staticFile("images/entities/".$item->entity->picture)?>">
                    </div>
                    <div class="data">
                        <? if ($item->source == "youtube"):?>
                            <div class="youtube">
                                <i class="fa fa-youtube"></i>
                         </div>
                        <? endif;?>
                        <div class="data-title">
                            <a class="red-link" href="<?=$item->link?>"><?=$item->title?></a>
                            <span class="body"><?=$item->body?></span>
                        </div>
                        <div class="data-controls">
                            <i class="header-button fa fa-sort-asc"></i>
                        </div>
                    </div>
                </div>
        <?endforeach?>
</div>