<?$this->headTitle("TwentyTags - Feed")?>
<div class="toTop">
    <button id="to-top-button" class="btn-small">
        <i class="fa fa-angle-double-up"></i> Up
    </button>
</div>
<div class="feed-container">
        <? foreach ($this->alerts as $item):?>
                <article class="alert-container">
                    <div class="entity">
                        <a class="red-link" title="<?=$item->entity->title?>" href="<?=$this->url(array("id"=>$item->entity, Model_Static_Functions::dashString($item->entity->title)=>""), "entity", false)?>">
                            <img src="<?=$this->staticFile("images/entities/".$item->entity->picture)?>">
                        </a>
                        <span class="date"><?=date("F jS, Y",strtotime($item->added));?></span>
                    </div>
                    <div class="data">
                        <h3>
                            <a class="red-link" href="<?=$item->link?>"><?=$item->title?></a>
                            <? if ($item->source == "youtube"):?>
                                <span class="youtube">
                                    <i class="fa fa-youtube"></i>
                                </span>
                            <? endif;?>
                        </h3>
                        <p>
                            <?=$item->body?>
                        </p>
                    </div>
                </article>
        <?endforeach?>
</div>

<script>
    $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y > 800) {
            $('.toTop').fadeIn();
        } else {
            $('.toTop').fadeOut();
        }
    });
    $(document).ready (function() {
        $("#to-top-button").click(function() {
            $('html, body').animate({ scrollTop: 0 }, 'slow');
        });
    });
</script>