<?$title = $this->mainTag == "What's hot" ? "Популярное" : $this->mainTag;?>
<?
$this->headTitle("TwentyTags - ".$title);
$this->headMeta()->appendName('keywords', "latest news, recent news, hitech news, IT news, sports news");
$this->headMeta()->appendName('description', "Stay updated. Get rid of noise. Receive the right news");
?>
    <h1 class="info lower">#<?=$this->mainTag == "What's hot" ? "Популярное" : $this->mainTag;?></h1>
    <? if (!$this->user) $isLogged = "user-not-logged";?>
    <?=$this->partial("partials/moretags.phtml", array("entities" => $this->entities))?>
<script>
    $(".to-follow-button").FollowEntity();

    var now = new Date().getTime();
    $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y >= ($(document).height() - $(window).height())) {
            if (new Date().getTime() - now > 1000) {
                var offset = $(window).data("offset");
                var url = "<?=$this->url(array('controller' => 'index', 'action' => 'moretags'), 'default', true)?>";
                var loadUrl = url + '/offset/' + offset + '/tag/' + '<?=$this->tag?>';
                loadMore(
                    $("article:last-child"),
                    loadUrl
                );
                now = new Date().getTime();
            }
        }
    });
    $(document).ready (function() {
        $(window).data("offset", "20");
    });

</script>