<?$this->headTitle("TwentyTags - Регистрация")?>
<div class="container padding-around-base">
    <? if ($this->mode == "addtag"):?>
        <p class="animate-slide-right-to-left alert-success margin-vertical-base"><i class="icon-lock-open"></i> Чтобы добавить тег, нужно войти</p>
    <?endif?>
<!--<h2 class="info">Регистрация и вход</h2>-->
<p class="margin-vertical-base lighten-text">
    Зарегистрируйтесь или войдите, используя свои данные
</p>
<?=$this->partial("partials/register.phtml", array("mode"=>$this->mode))?>