<div class="message-container">
    <div class="message-title">
       Notifications
    </div>
    <div class="message-description">
        We will post updates you're following to your Facebook feed if you wish. Turn this
        off if you don't want it
    </div>
    <div class="button-block">
        <button onclick="location.href='<?=$this->url(array(), "browse", false)?>'" class="button-text button-large">Turn on</button>
    </div>
</div>