<?=$this->forma(1)
    ->addBehavior('redirectUrl', '__fz/adm/entity')
    ->addField('text', 'title')
    ->fieldLabel("Entity title", true)
    ->fieldAttrib('size', '40')
    ->addField('textarea', 'description')
    ->fieldLabel("Entity description", true)
    ->fieldAttrib('size', '240')
    ->fieldAttrib('rows', 7)
    ->addField('textarea', 'link')
    ->fieldLabel("Entity link", true)
    ->fieldAttrib('size', '240')
    ->fieldAttrib('rows', 3)
    ->addField('textarea', 'picture')
    ->fieldLabel("Entity picture URL", true)
    ->fieldAttrib('size', '240')
    ->fieldAttrib('rows', 7)
    ->addField('submit')
    ->fieldAction(array('Model_Entity', 'create'))
    ->fieldValue("create entity")
?>

<table>
    <thead>
    <tr>
        <th>
            #
        </th>
        <th width="10%">
            entity
        </th>
        <th width="60%">
            entity description
        </th>
        <th width="30%">
            tags
        </th>
    </tr>
    </thead>
    <? foreach ($this->paginator as $item) :?>
        <tr>
            <td>
                <?=$item?>
            </td>
            <td>
                <img width="100px" src="<?=$this->staticFile("images/entities/".$item->picture)?>">
                <br/>
                <?=$this->partial('edit.phtml', array('element'=>'title'.$item, 'id'=>$item, 'class'=>'', 'text'=>$item->title, 'column'=>'title', 'table'=>'Entity'))?>
            </td>
            <td>
                <?=$this->partial('edit.phtml', array('element'=>'desc'.$item, 'id'=>$item, 'class'=>'', 'text'=>$item->description, 'column'=>'description', 'table'=>'Entity'))?>
                <br/>
                <?=$this->partial('edit.phtml', array('element'=>'link'.$item, 'id'=>$item, 'class'=>'', 'text'=>$item->link, 'column'=>'link', 'table'=>'Entity'))?>
            </td>
            <td>
                <b>Tagged as</b><br/>
                <?$tagged = Model_Tag::retrieveTaggedTagsByEntity($item);?>
                <? foreach ($tagged as $tag):?>
                    <a href="#"><?=$tag->value?></a><br/>
                <? endforeach?>
                <br/><br/>
                <b>All tags</b><br/>
                <? foreach ($this->tags as $tag):?>
                    <a style="cursor: pointer" onclick="tagEntity(<?=$item?>, <?=$tag?>)"><?=$tag->value?></a>&#160;&#160;<span id="<?=$item.$tag?>"></span><br/>
                <? endforeach?>
            </td>
        </tr>
    <? endforeach ?>
</table>
<script>
    function tagEntity(entity, tag) {
        var url = "<?=$this->url(array('action'=>'tagit'), 'fz__adm', true)?>";
        $.post(
            url,
            { 'entity': entity,  'tag': tag},
            function(data) {
                if (data == "OK") {
                    $("#"+entity+tag).html("saved");
                }
            }
        )
    }
</script>