<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>
<nav class="menu-icon-info desktop-only animate-show-slow" id="menu-icons">
    <li class="item-no-hover background-success">
        <a href="<?=$this->url(array(), "browse", false)?>">
            <img class="logo-image" src="<?=$this->staticFile("images/twentytags.svg")?>"/>
        </a>
    </li>
    <? if ($this->user):?>
        <?$logoutUrl = $this->url(array("action"=>"logout"), "logout", false);?>
        <?$followingUrl = $this->url(array(), "following", true);?>
        <?$addTagUrl = $this->url(array(), "addtag", true);?>
        <?$feedUrl = $this->url(array(), "feed", true);?>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button onclick="location.href='<?=$feedUrl?>'" class="button-info button-medium capitalize">лента</button>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button onclick="location.href='<?=$followingUrl?>'" class="button-info button-medium capitalize">мои теги</button>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button onclick="location.href='<?=$addTagUrl?>'" class="button-info button-medium capitalize">добавить</button>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color opens-menu-outter">
            <button class="button-info button-medium capitalize">меню</button>
        </li>
        <li class="item-no-hover padding-vertical-large center">
            <i id="icon-to-top" class="lighten-info large fa fa-arrow-up"></i>
        </li>
    <? else: ?>
        <?
        $loginUrl = $facebook->getLoginUrl(array(
            "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login"), "login", false)
        ));
        ?>
        <?
        $addTagUrlWithLogin = $facebook->getLoginUrl(array(
            "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login", "redirect"=>"addtag"), "login", false)
        ));
        ?>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button onclick="location.href='<?=$addTagUrl?>'" class="button-info button-medium capitalize"><i class="fa fa-bolt"></i> Войти</button>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button onclick="location.href='<?=$addTagUrl?>'" class="button-info button-medium capitalize"><i class="fa fa-plus-circle"></i> Добавить</button>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color">
            <button class="button-info button-medium opens-menu-outter capitalize"><i class="fa fa-bars"></i> меню</button>
        </li>
        <li class="item-no-hover padding-vertical-large center">
            <i id="icon-to-top" class="lighten-info large fa fa-arrow-up"></i>
        </li>
    <? endif;?>
</nav>
<nav class="container mobile-menu mobile-and-medium-only  background-info controls-text-color medium right">
    <div class="mobile-span2 logo-image-mobile background-success">
        <a href="<?=$this->url(array(), "browse", false)?>">
            <img src="<?=$this->staticFile("images/twentytags-mobile.svg")?>"/>
        </a>
    </div>
    <div class="mobile-span3 padding-around-base ">
        <i class="fa fa-bars opens-menu-outter"></i>
    </div>
    <div class="mobile-span2 padding-around-base ">
        <i class="fa fa-repeat"></i>
    </div>
    <div class="mobile-span2 padding-around-base ">
        <i class="fa fa-plus"></i>
    </div>
    <div class="mobile-span2 padding-around-base ">
        <i class="fa fa-folder-open"></i>
    </div>
</nav>
