<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>

<div class="menu-container" id="menu-container">
    <ul>
        <li class="logo-item">
            <a href="<?=$this->url(array(), $this->user ? "feed":"browse", false)?>">
                <img src="<?=$this->staticFile("images/logo.svg")?>"/>
            </a>
        </li>
        <li>
            <i id="tags-button" class="btn-header fa fa-bars"></i>
        </li>
            <? if ($this->user):?>
                <?$logoutUrl = $this->url(array("action"=>"logout"), "logout", false);?>
                <?$followingUrl = $this->url(array(), "following", true);?>
                <?$addTagUrl = $this->url(array(), "addtag", true);?>
            <li>
              <i onclick="location.href='<?=$followingUrl?>'" class="btn-header fa fa-th"></i>
            </li>
            <li>
                <i onclick="location.href='<?=$addTagUrl?>'" class="btn-header fa fa-plus"></i>
            </li>
            <li>
                <i title="Sign out" onclick="location.href='<?=$logoutUrl?>'" class="btn-header fa fa-external-link"></i>
            </li>
        <?else:?>
            <?
                $loginUrl = $facebook->getLoginUrl(array(
                    "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login"), "login", false)
                ));
            ?>
            <?
                $addTagUrlWithLogin = $facebook->getLoginUrl(array(
                    "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login", "redirect"=>"addtag"), "login", false)
                ));
            ?>
            <li>
                <i onclick="location.href='<?=$addTagUrlWithLogin?>'" class="btn-header fa fa-plus"></i>
            </li>
            <li>
                <i title="Sign up with Facebook" onclick="location.href='<?=$loginUrl?>'" class="btn-header fa fa-facebook-square"></i>
            </li>
        <?endif?>
    </ul>
    <div class="main-tag"><?=$this->mainTag?></div>
</div>
<script>
    $("#tags-button").click(function() {
        $("#menu-panel").toggleClass("slide-menu-right");
        $("#page-container").toggleClass("slide-page-container-right");
        $("#menu-container").toggleClass("menu-container-slide-right");
    });
</script>