<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>
<?$addTagUrlWithLogin = $this->url(array("mode"=>"addtag"), "register", true);?>
<nav class="menu-icon-info desktop-only animate-show-slow" id="menu-icons">
    <li class="item-no-hover background-success">
        <a href="<?=$this->url(array(), "browse", false)?>">
            <img class="logo-image" src="<?=$this->staticFile("images/twentytags.svg")?>"/>
        </a>
    </li>
    <? if ($this->user):?>
        <?$logoutUrl = $this->url(array("action"=>"logout"), "logout", false);?>
        <?$followingUrl = $this->url(array(), "following", true);?>
        <?$addTagUrl = $this->url(array(), "addtag", true);?>
        <?$feedUrl = $this->url(array(), "feed", true);?>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i class="opens-menu-outter icon-th-list-1 medium"></i><br/>
            <span class="small">разделы</span>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i onclick="location.href='<?=$feedUrl?>'" class="icon-cw medium"></i><br/>
            <span class="small">новости</span>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i onclick="location.href='<?=$followingUrl?>'" class="icon-vcard medium"></i><br/>
            <span class="small">мои теги</span>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i onclick="location.href='<?=$addTagUrl?>'" class="icon-plus-1 medium"></i><br/>
            <span class="small">новый тег</span>
        </li>
        <li class="item-no-hover padding-vertical-large center">
            <i id="icon-to-top" class="lighten-success medium icon-up-open"></i>
        </li>
    <? else: ?>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i class="opens-menu-outter icon-th-list-1 medium"></i><br/>
            <span class="small">разделы</span>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i onclick="location.href='<?=$addTagUrlWithLogin?>'" class="icon-plus-1 medium"></i><br/>
            <span class="small">новый тег</span>
        </li>
        <li class="item-no-hover padding-around-small controls-text-color center">
            <i onclick="location.href='<?=$this->url(array(), "register", true)?>'" class="icon-key-2 medium"></i><br/>
            <span class="small">вход</span>
        </li>
        <li class="item-no-hover padding-vertical-large center">
            <i id="icon-to-top" class="lighten-success medium icon-up-open"></i>
        </li>
    <? endif;?>
</nav>
<nav class="container mobile-menu mobile-and-medium-only  background-info controls-text-color medium right">
    <div class="mobile-span2 logo-image-mobile background-success">
        <a href="<?=$this->url(array(), "browse", false)?>">
            <img src="<?=$this->staticFile("images/twentytags-mobile.svg")?>"/>
        </a>
    </div>
    <div class="mobile-span3 padding-around-base ">
        <i class="icon-th-list-1 opens-menu-outter"></i>
    </div>
    <? if ($this->user):?>
        <div class="mobile-span2 padding-around-base ">
            <i onclick="location.href='<?=$feedUrl?>'" class="icon-cw"></i>
        </div>
        <div class="mobile-span2 padding-around-base ">
            <i onclick="location.href='<?=$addTagUrl?>'"  class="icon-plus-1"></i>
        </div>
        <div class="mobile-span2 padding-around-base ">
            <i onclick="location.href='<?=$followingUrl?>'" class="icon-vcard"></i>
        </div>
    <?else:?>
        <div class="mobile-span4 padding-around-base right">
            <i onclick="location.href='<?=$addTagUrlWithLogin?>'" class="icon-plus-1"></i>
        </div>
        <div class="mobile-span2 padding-around-base ">
            <i onclick="location.href='<?=$this->url(array(), "register", true)?>'" class="icon-key-2"></i>
        </div>
    <?endif?>
</nav>
