<?
require_once('Model/Facebook/facebook.php');
$config = array(
    'appId' => '706201236078444',
    'secret' => 'fabe992657dcffefd59099502cdf0ce9',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
);
$facebook = new Facebook($config);
?>
<? foreach ($this->entities as $item):?>


    <article class="container">
<!--        <div class="mobile-span2 right desktop-and-medium-only">-->
<!--            <a href="--><?//=$this->url(array("id"=>$item, Model_Static_Functions::dashString($item->title)=>""), "entity", false)?><!--">-->
<!--                <img title="--><?//=$item->title?><!--" src="--><?//=$this->staticFile("images/entities/".$item->picture)?><!--">-->
<!--            </a>-->
<!--        </div>-->
        <div class="span7 no-padding padding-vertical-small">
                <a class="lower darken-info medium" title="<?=$item->title?>" href="<?=$this->url(array("id"=>$item, Model_Static_Functions::dashString($item->title)=>""), "entity", false)?>"><?=$item->title?></a><br/>
            <?$tagged = Model_Tag::retrieveTaggedTagsByEntity($item);?>
            <? foreach ($tagged as $tag):?>
                <a class="info lower" href="<?=$this->url(array("id"=>$tag, Model_Static_Functions::dashString($tag->value)=>""), "tags", false)?>"><?=$tag->value?></a>&#160;
            <? endforeach?>
<!--            <p>-->
<!--                --><?//=$item->description?>
<!--            </p>-->
        </div>
        <div class="mobile-span2 desktop-and-medium-only">
            <p class="nowrap no-padding">
                <? if ($item->alerts > 0):?>
                    <span class="warning"><b><?=$item->alerts?></b></span>&#160;
                <?endif?>
                <? if ($item->today > 0):?> /
                    <span class="success"><b><?=$item->today?></b></span>
                <?endif?>
            </p>
        </div>
        <div class="span3 no-padding">
            <div id="item-follow-button-<?=$item?>" class="item-follow-button <?=$isSaved == true ? "make-visible":""?>">
                <button id="follow-<?=$item?>" class="button-success button-small f-span12 capitalize to-follow-button <?=$isLogged?> <?=$isSaved ? " followed":""?>">
                    <? if (!$this->user):?>
                        <div class="login-urls" id="login-url-<?=$item?>">
                            <?
                            $loginUrl = $facebook->getLoginUrl(array(
                                "redirect_uri" => WEBSITE_URL.$this->url(array("action"=>"login", "follow"=>$item), "login", false)
                            ));
                            echo $loginUrl;
                            ?>
                        </div>
                    <?endif?>
                    <?=$isSaved ? "Отписаться" : "Подписаться"?>
                </button>
            </div>
        </div>
<!--        <div class="unit10 center medium lighten-text">-->
<!--            <i class="fa fa-chevron-up lighten-success"></i><br/>-->
<!--            <span class="small">170</span><br/>-->
<!--            <i class="fa fa-chevron-down lighten-info"></i>-->
<!--        </div>-->
    </article>
<?endforeach?>
