<? foreach ($this->alerts as $item):?>

    <article class="container padding-vertical-medium">
        <? $unit = "unit80";?>
        <? if ($item->picture): ?>
            <? $unit = "unit55";?>
            <div class="unit25 right">
                <? if ($this->mode == "entity"):?>
                    <? $imgUrl = $item->link?>
                    <? $target = "target='_blank'";?>
                <? else: ?>
                    <? $imgUrl = $this->url(array("id"=>$item->entity, Model_Static_Functions::dashString($item->entity->title)=>""), "entity", false)?>
                <?endif?>
                <a <?=$target?> title="<?=$item->entity->title?>" href="<?=$imgUrl?>">
                    <? if ($item->picture): ?>
                        <img src="<?=$this->staticFile("images/alerts/".$item->picture)?>"><br/>
                    <? else: ?>
                        <!-- <img src="<?=$this->staticFile("images/entities/".$item->entity->picture)?>">-->
                    <? endif ?>
                </a>
            </div>
        <?endif?>
        <div class="<?=$unit?>">
            <h3>
                <? if (!$this->entity):?>
                    <a class="lower info" href="<?=$this->url(array("id"=>$item->entity, Model_Static_Functions::dashString($item->entity->title)=>""), "entity", false)?>"><i class="icon-hash warning"></i> <?=$item->entity->title?></a>&#160;&#160;
                <? endif?>
                <a class="lower lighten-info" target="_blank" href="<?=$item->link?>"><?=$item->title?></a>
            </h3>
            <p>
                <?=$item->body?>
            </p>
        </div>
        <div class="unit10 desktop-only">
            <? if ($item->source == "youtube"):?>
                <h1>
                    <a class="no-underline" target="_blank" href="<?=$item->link?>"><i class="fa fa-play-circle-o large lighten-success"></i></a>
                </h1>
            <? endif;?>
        </div>
        <div class="unit10 lighten-info">
            <?=date("m/j/Y",strtotime($item->added));?>
        </div>
    </article>
<?endforeach?>
